name: Deploy Images to GitHub Container Registry (GHCR)

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Docker Image'
            #repo and image now really ought to be parameterized..
            run: |
              docker build . --tag ghcr.io/hvl71/weatherapi:latest
              docker push ghcr.io/hvl71/weatherapi:latest
