name: Build and Push Image to Container Registry

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      build-push-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to Container Registry'
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Docker Image'
            #repo and image now really ought to be parameterized..
            run: |
              docker build . --tag ghcr.io/hvl71/weatherapi:latest
              #be sure to allow push to registry as described on the below link
              #https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions
              docker push ghcr.io/hvl71/weatherapi:latest
